config/routes.rb
Rails.application.routes.draw do
  resources:students
  resources:exams
  resources:teachers
  resources:reports
  resources:payments
  resources:pockets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    def new
        @exam = Exam.new
    end

    def create
        exam = Exam.new (resources_params)
        exam.save 
        redirect_to exams_path
        flash[:notice] = 'Exam has been created'
    end

    def edit
        @exam = Exam.find(params[:id])
    end

    def update
        @exam = Exam.find(params[:id])
        @exam.update(resources_params)
        flash[:notice] = 'Exam has been update'
        redirect_to exams_path(@exam)
    end

    def destroy
        @exam = Exam.find(params[:id])
        @exam.destroy
        flash[:notice] = 'Exam has been destroy'
        redirect_to exams_path(@exam)
    end

    def index
        @exams = Exam.all
    end
    
    def show
        id = params[:id]
        @exam = Exam.find(id)
    end

    private  
    def resources_params
        params.required(:exam).permit(:title, :hasil, :mapel, :duration, :nilai, :status, :level, :student_id)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new
        @payment = Payment.new
    end

    def create
        payment = Payment.new (resources_params)
        payment.save 
        redirect_to payments_path
        flash[:notice] = 'Payment has been created'
    end

    def edit
        @payment = Payment.find(params[:id])
    end

    def update
        @payment = Payment.find(params[:id])
        @payment.update(resources_params)
        flash[:notice] = 'Payment has been update'
        redirect_to payments_path(@exam)
    end

    def destroy
        @payment = Payment.find(params[:id])
        @payment.destroy
        flash[:notice] = 'Payment has been destroy'
        redirect_to payments_path(@exam)
    end

    def index
        @payments = Payment.all
    end
    
    def show
        id = params[:id]
        @payment = Payment.find(id)
    end

    private  
    def resources_params
        params.required(:payment).permit(:id_transaction, :status, :upload)
    end
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
    def new
        @pocket = Pocket.new
    end

    def create
        pocket = Pocket.new (resources_params)
        pocket.save 
        redirect_to pockets_path
        flash[:notice] = 'Pocket has been created'
    end

    def edit
        @pocket = Pocket.find(params[:id])
    end

    def update
        @pocket = Pocket.find(params[:id])
        @pocket.update(resources_params)
        flash[:notice] = 'Pocket has been update'
        redirect_to pockets_path(@pocket)
    end

    def destroy
        @pocket = Pocket.find(params[:id])
        @pocket.destroy
        flash[:notice] = 'Pocket has been destroy'
        redirect_to pockets_path(@exam)
    end

    def index
        @pockets = Pocket.all
    end
    
    def show
        id = params[:id]
        @pocket = Pocket.find(id)
    end

    private  
    def resources_params
        params.required(:pocket).permit(:balance, :student_id, :teacher_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    def new
        @report = Report.new
    end

    def create
        report = Report.new (resources_params)
        report.save 
        redirect_to reports_path
        flash[:notice] = 'Report has been created'
    end

    def edit
        @report = Report.find(params[:id])
    end

    def update
        @report = Report.find(params[:id])
        @report.update(resources_params)
        flash[:notice] = 'Report has been update'
        redirect_to reports_path(@report)
    end

    def destroy
        @report = Report.find(params[:id])
        @report.destroy
        flash[:notice] = 'Exam has been destroy'
        redirect_to reports_path(@report)
    end

    def index
        @reports = Report.all
    end
    
    def show
        id = params[:id]
        @report = Report.find(id)
    end

    private  
    def resources_params
        params.required(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def new
        @student = Student.new
    end

    def create
        student = Student.new (resources_params)
        student.save 
        redirect_to students_path
        flash[:notice] = 'Student has been created'
    end

    def edit
        @student = Student.find(params[:id])
    end

    def update
        @student = Student.find(params[:id])
        @student.update(resources_params)
        flash[:notice] = 'Student has been update'
        redirect_to student_path(@student)
    end

    def destroy
        @student = Student.find(params[:id])
        @student.destroy
        flash[:notice] = 'Student has been destroy'
        redirect_to students_path(@student)
    end

    def index
        @students = Student.all
    end
    
    def show
        id = params[:id]
        @student = Student.find(id)
    end

    private  
    def resources_params
        params.required(:student).permit(:name, :username, :age, :kelas, :address, :city, :NIK)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def new
        @teacher = Teacher.new
    end

    def create
        teacher = Teacher.new (resources_params)
        teacher.save 
        redirect_to teachers_path
        flash[:notice] = 'Teacher has been created'
    end

    def edit
        @teacher = Teacher.find(params[:id])
    end

    def update
        @teacher = Teacher.find(params[:id])
        @teacher.update(resources_params)
        flash[:notice] = 'Teacher has been update'
        redirect_to teachers_path(@teacher)
    end

    def destroy
        @teacher = Teacher.find(params[:id])
        @teacher.destroy
        flash[:notice] = 'Teacher has been destroy'
        redirect_to teachers_path(@teacher)
    end

    def index
        @teachers = Teacher.all
    end
    
    def show
        id = params[:id]
        @teacher = Teacher.find(id)
    end

    private  
    def resources_params
        params.required(:teacher).permit(:NIK, :nama, :age, :kelas, :mapel)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/exams/edit.html.erb
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>
    
    <%= f.submit "Save" %>
    <%= link_to 'Back', exams_path %>
    
    
<% end %>

app/views/exams/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container">

<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Title</th>
        <th>Hasil</th>
        <th>Mapel</th>
        <th>Duration</th>
        <th>Nilai</th>
        <th>Status</th>
        <th>Level</th>
        <th>Student ID</th>
        <th>Action</th>

    </tr>
    </thead>

    <tbody>
    <% @exams.each do |exam| %>
    <tr>
        <td><%= exam.title %></td>
        <td><%= exam.hasil %></td>
        <td><%= exam.mapel %></td>
        <td><%= exam.duration %></td>
        <td><%= exam.nilai %></td>
        <td><%= exam.status %></td>
        <td><%= exam.level %></td>
        <td><%= exam.student_id %></td>
        <td>
        <%= link_to 'Detail', exam_path(exam), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_exam_path(exam), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', exam_path(exam) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>

    </tr>
    <% end %>
    </tbody>

</table> 
<%= link_to 'New Exam', new_exam_path(), class:"btn btn-primary" %>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>

app/views/exams/new.html.erb
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>
    
    <%= f.submit "Save" %>
    <%= link_to 'Back', exams_path %>
    
    
<% end %>

app/views/payments/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container">
    <table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>ID Transaction</th>
        <th>Status</th>
        <th>Upload</th>
        <th>Action</th>
    </tr>
    </thead>

    <tbody>
    <% @payments.each do |payment| %>
    <tr>
        <td><%= payment.id_transaction %></td>
        <td><%= payment.status %></td>
        <td><%= payment.upload %></td>
        <td>
        <%= link_to 'Detail', payment_path(payment), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_payment_path(payment), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', payment_path(payment) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>

    </tr>
    <% end %>
    </tbody>

</table>
<%= link_to 'New Payment', new_payment_path(), class:"btn btn-primary" %>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>

app/views/payments/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

ID Transaction : <%= @payment.id_transaction %> </br>
Status : <%= @payment.status %> </br>
Upload : <%= @payment.upload %> </br>

<%= link_to 'Back', payments_path %> 

app/views/pockets/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container">

<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Balance</th>
        <th>Student ID</th>
        <th>Teacher ID</th>
        <th>Action</th>
    </tr>
    </thead>

    <tbody>
    <% @pockets.each do |pocket| %>
    <tr>
        <td><%= pocket.balance %></td>
        <td><%= pocket.student_id %></td>
        <td><%= pocket.teacher_id %></td>
        <td>
        <%= link_to 'Detail', pocket_path(pocket), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_pocket_path(pocket), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', pocket_path(pocket) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %></td>

    </tr>
    <% end %>
    </tbody>

</table> 
<%= link_to 'New Payment', new_pocket_path(), class:"btn btn-primary" %>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>

app/views/reports/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container">

<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Title</th>
        <th>Hasil</th>
        <th>Mapel</th>
        <th>Teacher ID</th>
        <th>Student ID</th>
        <th>Action</th>
    </tr>
    </thead>

    <tbody>
    <% @reports.each do |report| %>
    <tr>
        <td><%= report.title %></td>
        <td><%= report.hasil %></td>
        <td><%= report.mapel %></td>
        <td><%= report.teacher_id %></td>
        <td><%= report.student_id %></td>
        <td>
        <%= link_to 'Detail', report_path(report), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_report_path(report), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', report_path(report), method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %></td>

    </tr>
    <% end %>
    </tbody>

</table> 
<%= link_to 'New Report', new_report_path(), class:"btn btn-primary" %>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>

app/views/students/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container">

<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Name</th>
        <th>Username</th>
        <th>Age</th>
        <th>Kelas</th>
        <th>Address</th>
        <th>City</th>
        <th>NIK</th>
        <th>Action</th>
    </tr>
    </thead>

    <tbody>
    <% @students.each do |student| %>
    <tr>
        <td><%= student.name %></td>
        <td><%= student.username %></td>
        <td><%= student.age %></td>
        <td><%= student.kelas %></td>
        <td><%= student.address %></td>
        <td><%= student.city %></td>
        <td><%= student.NIK %></td>
        <td>
        <%= link_to 'Detail', student_path(student), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_student_path(student), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', student_path(student) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>

    </tr>
    <% end %>
    </tbody>

</table> 
<%= link_to 'New Student', new_student_path(), class:"btn btn-primary" %>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>

    

app/views/teachers/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container">


<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>NIK</th>
        <th>Nama</th>
        <th>Age</th>
        <th>Kelas</th>
        <th>Mapel</th>
        <th>Action</th>
    </tr>
    </thead>

    <tbody>
    <% @teachers.each do |teacher| %>
    <tr>
        <td><%= teacher.NIK %></td>
        <td><%= teacher.nama %></td>
        <td><%= teacher.age %></td>
        <td><%= teacher.kelas %></td>
        <td><%= teacher.mapel %></td>
        <td>
        <%= link_to 'Detail', teacher_path(teacher), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_teacher_path(teacher), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', teacher_path(teacher) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>

    </tr>
    <% end %>
    </tbody>

</table> 
<%= link_to 'New Teacher', new_teacher_path(), class:"btn btn-primary" %>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>